### ISSUE TITLE
Project fails with error: expected hoisted manifest

### ISSUE THREAD

**Issue by dagerber** [manfredsteyer/module-federation-plugin-example#25]
Env:
node -v ==> v16.16.0
npm -v ==> 8.11.0
yarn -v ==> 1.22.18

```
git clone https://github.com/manfredsteyer/module-federation-plugin-example.git --branch starter
cd module-federation-plugin-example.git
yarn
```

Results in:

error An unexpected error occurred: "expected hoisted manifest for \"ngx-build-plus#@angular-devkit/build-angular#webpack-dev-server#webpack-dev-middleware#webpack\"".

➜  module-federation-plugin-example git:(starter) cat yarn-error.log
Arguments:
  /usr/local/Cellar/node@16/16.16.0/bin/node /usr/local/Cellar/yarn/1.22.18/libexec/bin/yarn.js

PATH:
  <removed>

Yarn version:
  1.22.18

Node version:
  16.16.0

Platform:
  darwin x64

Trace:
  Invariant Violation: expected hoisted manifest for "ngx-build-plus#@angular-devkit/build-angular#webpack-dev-server#webpack-dev-middleware#webpack"
      at invariant (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:2314:15)
      at _loop2 (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:91022:9)
      at PackageHoister.init (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:91092:19)
      at PackageLinker.getFlatHoistedTree (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:48541:20)
      at PackageLinker.<anonymous> (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:48552:27)
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:310:30)
      at /usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:328:14
      at new Promise (<anonymous>)
      at new F (/usr/local/Cellar/yarn/1.22.18/libexec/lib/cli.js:5301:28)

npm manifest:
  {
    "name": "mf-demo",
    "version": "0.0.0",
    "scripts": {
      "ng": "ng",
      "start": "npm run start:shell",
      "start:shell": "ng serve shell  -o --port 5000",
      "start:mfe1": "ng serve mfe1 -o --port 3000",
      "start:all": "concurrently \"npm run start:shell\" \"npm run start:mfe1\" ",
      "build:shell": "ng build shell --prod",
      "build:mfe1": "ng build mfe1 --prod",
      "serve:dist": "concurrently \"serve dist/shell -l 5000 -s\" \"serve dist/mfe1 -l 3000 -s\" ",
      "build": "npm run build:shell && npm run build:mfe1",
      "test": "ng test",
      "lint": "ng lint",
      "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
      "@angular-architects/module-federation": "^14.3.0",
      "@angular/animations": "14.0.0",
      "@angular/common": "14.0.0",
      "@angular/compiler": "14.0.0",
      "@angular/core": "14.0.0",
      "@angular/forms": "14.0.0",
      "@angular/platform-browser": "14.0.0",
      "@angular/platform-browser-dynamic": "14.0.0",
      "@angular/router": "14.0.0",
      "@nrwl/workspace": "^10.3.0",
      "concurrently": "^5.3.0",
      "rxjs": "~6.6.0",
      "tslib": "^2.0.0",
      "zone.js": "~0.11.4"
    },
    "devDependencies": {
      "@angular-devkit/architect": "^0.1400.0",
      "@angular-devkit/build-angular": "14.0.0",
      "@angular/cli": "14.0.0",
      "@angular/compiler-cli": "14.0.0",
      "@types/jasmine": "~3.5.0",
      "@types/jasminewd2": "~2.0.3",
      "@types/node": "^12.11.1",
      "codelyzer": "^6.0.0",
      "jasmine-core": "~3.6.0",
      "jasmine-spec-reporter": "~5.0.0",
      "karma": "~6.3.9",
      "karma-chrome-launcher": "~3.1.0",
      "karma-coverage": "~2.0.3",
      "karma-jasmine": "~4.0.0",
      "karma-jasmine-html-reporter": "^1.5.0",
      "ngx-build-plus": "^14.0.0",
      "protractor": "~7.0.0",
      "serve": "^11.3.2",
      "ts-node": "~8.3.0",
      "tslint": "~6.1.0",
      "typescript": "~4.7.3"
    }
  }

yarn manifest:
  No manifest

Lockfile:
  No lockfile

**Comment by dagerber** [comment]
Deleted node_modules and yarn-cache. Fresh checkout, works now
