### ISSUE TITLE
ng test error: flights.module.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by careywalker** [manfredsteyer/module-federation-plugin-example#4]
Hi, thanks for providing this sample.

When I run ng test, I get the following error:

PS C:\Code\Repos\Git\module-federation-plugin-example-starter> ng test --browsers ChromeHeadless
- Generating browser application bundles...(node:71312) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.
\ Generating browser application bundles (phase: building)...26 02 2021 11:44:10.726:WARN [karma]: No captured browser, open http://localhost:9877/
26 02 2021 11:44:10.753:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9877/
26 02 2021 11:44:10.755:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
26 02 2021 11:44:10.766:INFO [launcher]: Starting browser ChromeHeadless
\ Generating browser application bundles (phase: sealing)...
./projects/mfe1/src/app/flights/flights.module.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: C:\Code\Repos\Git\module-federation-plugin-example-starter\projects\mfe1\src\app\flights\flights.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Code\Repos\Git\module-federation-plugin-example-starter\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:957:23)
    at plugin.done.then (C:\Code\Repos\Git\module-federation-plugin-example-starter\node_modules\@ngtools\webpack\src\loader.js:43:31)

I haven't managed to fix the issue so just checking to see if you had any ideas.

**Comment by Santiago-Moreno** [comment]
I noticed this issue as well and managed to fix it by including all typescript files (not just spec and d.ts) in every tsconfig.
This is how the updated include in every tsconfig looks like: 
``` 
"include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts",
    "src/**/*.ts"
  ]
```  

After updating the tsconfigs it compiles fine, though a new error will be thrown once a browser instance gets started:  
`Uncaught Error: Shared module is not available for eager consumption`
This is an issue with the way microfrontends get loaded asynchronously (see [this link](https://medium.com/dev-genius/module-federation-advanced-api-inwebpack-5-0-0-beta-17-71cd4d42e534) and [this one](https://webpack.js.org/concepts/module-federation/) for more information).
This issue can be fixed by moving the code from _test.ts_ into a new file _bootstrap-test.ts_.
_test.ts_ then just has the following line of code:
`import('./bootstrap-test')`
This also has to be done for every _test.ts_ file.
